[package]
name = "giants-scraper"
version.workspace = true
edition.workspace = true

[dependencies]
giants-models = { path = "../models" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
