[package]
name = "gtm-scraper"
version.workspace = true
edition.workspace = true

[dependencies]
gtm-models = { path = "../models" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
